### ISSUE TITLE
500 error when clicking Registration

### ISSUE THREAD

**Issue by keamo** [pinry/docker-pinry#2]
Hello,

Installed docker-pinry on a fresh install of Ubuntu 14.04 LTS.  When I click on 'Register'(after filling in username/email/password, I get the 500 Something went wrong! error.

Server specs: Intel x5560x4, 4G RAM, 40G HD.

Install instructions were great BTW.  Thanks!

**Comment by qjebbs** [comment]
same issue

**Comment by overshard** [comment]
Fixed in the latest update.
