### ISSUE TITLE
Enable Docker hub autobuild

### ISSUE THREAD

**Issue by rtau** [pinry/docker-pinry#21]
I've tried to merge the content of this repository into pinry/pinry thus I could use Docker hub to automatically build the Docker image. Any chance it could be merged so that the Docker images is updated automatically?

Please take a look at the Docker image here: https://hub.docker.com/r/rtau/pinry

**Comment by winkidney** [comment]
@rtau Thanks for your efforts to build them together.
I wounder why your want to build them together, for  convenience to build docker or any other reason?

I have no concern about it and just wonder why you want to build them together : )
Maybe two repo for docker-mode and source-repo is not so nice for users I guess, but docker-pinry now works well as we expected.

@overshard What do you think about it?

**Comment by rtau** [comment]
The main problem is the pinry docker image is not automatically updated on hub.docker.com with new release.

If the Dockerfile is in the same repository, we could make Docker Hub build and publish the new image with the code as at that tag/branch automatically. That had been setup on my fork at the moment, monitoring new commit on master branch and new tags.

**Comment by rtau** [comment]
The fork is here: https://github.com/rtau-trial/pinry

It is just the latest master with those files from docker-pinry added, and my attempt to reduce the Docker image build time and size.

**Comment by overshard** [comment]
I think building in the docker files for Pinry now is fine. It seems to be one of the primary ways of deployment. We should definitely merge docker-pinry with the main pinry repo.

**Comment by rtau** [comment]
Thanks for the comments, I have created 2 pull request on the pinry repository on this, for merging the docker-pinry content and my attempt to optimize the image build separately:
https://github.com/pinry/pinry/pull/142
https://github.com/pinry/pinry/pull/143

Please review and comment.

**Comment by rtau** [comment]
As https://github.com/pinry/pinry/pull/142 had been merged, I'd like to treat this issue as resolved.
